name: openapi_getx
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  tuple: ^2.0.2
  json_annotation:
  openapi:
    path: ./openapi
  equatable: ^2.0.5
  google_fonts: 6.1.0
  dartz: ^0.10.1
  dio: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:


flutter:
  uses-material-design: true

  assets:
    - assets/image/

  